export default {
  plus: { url: '/ui/plus.svg', alt: 'Adicionar' },
  minus: { url: '/ui/minus.svg', alt: 'Remover' },
  arrowRight: { url: '/ui/arrow-right.svg', alt: 'Seta para a direita' },
  arrowLeft: { url: '/ui/arrow-left.svg', alt: 'Seta para a esquerda' },
  home: { url: '/ui/home.svg', alt: 'Casa' },
  edit: { url: '/ui/edit.svg', alt: 'Lápis' },
  options: { url: '/ui/options.svg', alt: 'Opções' },
  close: { url: '/ui/close.svg', alt: 'Fechar' },
  delete: { url: '/ui/delete.svg', alt: 'Deletar' },
  branch: { url: '/ui/branch.svg', alt: 'Branch' },
  statistics: { url: '/ui/statistics.svg', alt: 'Estatísticas' },
  check: { url: '/ui/check.svg', alt: 'Ok' },
  clock: { url: '/ui/clock.svg', alt: 'Relógio' },
  play: { url: '/ui/play.svg', alt: 'Play' },
  refresh: { url: '/ui/refresh.svg', alt: 'Atualizar' },
  pause: { url: '/ui/pause.svg', alt: 'Pausar' },
  quantity: { url: '/ui/quantity.svg', alt: 'Quantidade' },
};
